[build]
  command = "bash build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.19.0"
  NPM_FLAGS = "--legacy-peer-deps --no-cache --no-audit --no-fund"
  NPM_CONFIG_CACHE = "/opt/buildhome/.npm"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_PREFER_OFFLINE = "false"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
